### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 while compiling lzss.c and img4.c

### ISSUE THREAD

**Issue by c1der** [xerub/img4lib#1]
While compiling lzss.c and img4.c with 
`gcc -o img4 -L/usr/local/openssl-1.0.2h/lib -I/usr/local/openssl-1.0.2h/include/openssl lzss.o img4.o libDER/DER_Encode.o libDER/DER_Decode.o libDER/oids.o libvfs/vfs_file.o libvfs/vfs_mem.o libvfs/vfs_sub.o libvfs/vfs_enc.o libvfs/vfs_lzss.o libvfs/vfs_lzfse.o libvfs/vfs_img4.o -lcrypto` 
I get: 
`Undefined symbols for architecture x86_64:
  "_lzfse_decode_buffer", referenced from:
      _lzfse_reopen in vfs_lzfse.o
  "_lzfse_decode_scratch_size", referenced from:
      _lzfse_reopen in vfs_lzfse.o
  "_lzfse_encode_buffer", referenced from:
      _lzfse_fsync in vfs_lzfse.o
  "_lzfse_encode_scratch_size", referenced from:
      _lzfse_fsync in vfs_lzfse.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I am on Mac OSX 10.12

**Comment by xerub** [comment]
Repeat after me: I am unable to read README.md
