### ISSUE TITLE
unable to build img4lib

### ISSUE THREAD

**Issue by matteyeux** [xerub/img4lib#4]
Since commit [d273abb](https://github.com/xerub/img4lib/commit/d273abbcb0a57288df9a9ac320b97795110370dd) I am unable to build img4lib.
Error : 
```
libvfs/vfs_img4.c:354:8: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     rsa->n = BN_bin2bn(pkeyComponents[0].data, pkeyComponents[0].length, NULL);
```
OS/version : 
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

I also tested on Ubuntu 18.04, same error.

**Comment by remixmaster34** [comment]
similar error on Mac, clang error different but same line:column

libvfs/vfs_img4.c:354:8: error: incomplete definition of type 'struct rsa_st'
    rsa->n = BN_bin2bn(pkeyComponents[0].data, pkeyComponents[0].length, NULL);
    ~~~^

**Comment by xerub** [comment]
OpenSSL 1.1.0 API changes, which I tried to address in ec8379388ccdcb169d91e502213db97fb79c11d7

For Mac, it's easier to pass COMMONCRYPTO=1 to make
For Mac/Linux, one could use corecrypto (and consequently pass CORECRYPTO=1 to make), but I assume copying the corecrypto sources in place is more trouble than it's worth...

**Comment by soup6020** [comment]
This is still an issue

**Comment by xerub** [comment]
I merged a PR. Can you please try again?

**Comment by soup6020** [comment]
Not for another few hours, but yeah when I'm home from work.

**Comment by matteyeux** [comment]
Hey,

I just tested to build on master branch and it worked. 

Thank you

**Comment by xerub** [comment]
Nice. Thanks
