### ISSUE TITLE
Build fails on Linux with libssl 1.0.2 

### ISSUE THREAD

**Issue by soup6020** [xerub/img4lib#6]
I have downgraded my ssl just to get this thing to compile, and it still spits out errors at me:

```ar crus libimg4.a lzss.o libDER/DER_Encode.o libDER/DER_Decode.o libDER/oids.o libvfs/vfs_file.o libvfs/vfs_mem.o libvfs/vfs_sub.o libvfs/vfs_enc.o libvfs/vfs_lzss.o libvfs/vfs_lzfse.o libvfs/vfs_img4.o
ar: `u' modifier ignored since `D' is the default (see `U')
gcc -o img4 -g img4.o lzss.o libDER/DER_Encode.o libDER/DER_Decode.o libDER/oids.o libvfs/vfs_file.o libvfs/vfs_mem.o libvfs/vfs_sub.o libvfs/vfs_enc.o libvfs/vfs_lzss.o libvfs/vfs_lzfse.o libvfs/vfs_img4.o libimg4.a -llzfse -lssl -lcrypto -lcrypto
/usr/bin/ld: libvfs/vfs_img4.o: in function `dovalidate':
/home/ezra/git/img4lib/libvfs/vfs_img4.c:1952: undefined reference to `EVP_cleanup'
/usr/bin/ld: /home/ezra/git/img4lib/libvfs/vfs_img4.c:1954: undefined reference to `CRYPTO_cleanup_all_ex_data'
collect2: error: ld returned 1 exit status
make: *** [Makefile:141: img4] Error 1

```

**Comment by EWouters** [comment]
Have you tried OpenSSL 1.1.0? It seems commit ec8379388ccdcb169d91e502213db97fb79c11d7 refers to that version.

**Comment by onny** [comment]
Here's a PKGBUILD I made for Archlinux which seems to work https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=img4lib-git

**Comment by soup6020** [comment]
> Have you tried OpenSSL 1.1.0? It seems commit [ec83793](https://github.com/xerub/img4lib/commit/ec8379388ccdcb169d91e502213db97fb79c11d7) refers to that version.

that's the exact version I used initially

**Comment by xerub** [comment]
Ugh, I guess I should get rid of those function calls: EVP_cleanup and friends. I didn't know they were removed from the library. They shouldn't affect functionality AFAICR...
