### ISSUE TITLE
corecrypto/cc_clear.c:1:6: error: expected ';' after top level declarator

### ISSUE THREAD

**Issue by m1337v** [xerub/img4lib#7]
if I try to compile with `make CORECRYPTO=1`
I get the following error:
`corecrypto/cc_clear.c:1:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
https://developer.apple.com/security/
^
corecrypto/cc_clear.c:1:6: error: expected ';' after top level declarator
https://developer.apple.com/security/
     ^
     ;
1 warning and 1 error generated.
make: *** [corecrypto/cc_clear.o] Error 1`

**Comment by xerub** [comment]
the corecrypto sources are intentionally broken, because of apple license. you'd have to build with OpenSSL (for linux) or COMMONCRYPTO for macOS -- unless you're willing to cherry-pick the real sources from the apple website.

**Comment by dietmerc** [comment]
> the corecrypto sources are intentionally broken, because of apple license. you'd have to build with OpenSSL (for linux) or COMMONCRYPTO for macOS -- unless you're willing to cherry-pick the real sources from the apple website.

sus.

**Comment by dtmrc** [comment]
> the corecrypto sources are intentionally broken, because of apple license. you'd have to build with OpenSSL (for linux) or COMMONCRYPTO for macOS -- unless you're willing to cherry-pick the real sources from the apple website.

@xerub  could you show an example of macos build config using OpenSSL?
